# Use root/example as user/password credentials
version: '3.8'

services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: copystagram
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - /etc/letsencrypt/live/rta.kr/fullchain.pem:/etc/ssl/live/fullchain1.pem
      - /etc/letsencrypt/live/rta.kr/privkey.pem:/etc/ssl/live/privkey1.pem
      - ./static:/stellar-wallet-backend/public
    extra_hosts:
      - "host.docker.internal:host-gateway"

configs:
  nginx-config:
    file: "./nginx.conf"